# Generated by Django 4.2 on 2024-01-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customer_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_basic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_connected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_premium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='meta_key',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
