# Generated by Django 4.2 on 2024-01-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_customer_is_basic_customer_is_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='walletkey',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
